export const ACTION_TYPES = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT: 'SET_PRODUCT',
	ADD_PRODUCT_INTO_CART: 'ADD_PRODUCT_INTO_CART',
	DELETE_PRODUCT_FROM_CART: 'DELETE_PRODUCT_FROM_CART',
	DECREMENT_COUNT_OF_PRODUCT: 'DECREMENT_COUNT_OF_PRODUCT',
	INCREMENT_COUNT_OF_PRODUCT: 'INCREMENT_COUNT_OF_PRODUCT',
	CLEAN_CART: 'CLEAN_CART',
};
