export const ACTION_TYPES = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT: 'SET_PRODUCT',
	ADD_PRODUCT_INTO_CART: 'ADD_PRODUCT_INTO_CART',
	DELETE_PRODUCT_FROM_CART: 'DELETE_PRODUCT_FROM_CART',
	DECREMENT_COUNT_OF_PRODUCT: 'DECREMENT_COUNT_OF_PRODUCT',
	INCREMENT_COUNT_OF_PRODUCT: 'INCREMENT_COUNT_OF_PRODUCT',
	CLEAN_CART: 'CLEAN_CART',
	GET_CATEGORIES: 'GET_CATEGORIES',
	ADD_CHECKED_CATEGORY: 'ADD_CHECKED_CATEGORY',
	REMOVE_CHECKED_CATEGORY: 'REMOVE_CHECKED_CATEGORY',
	CHANGE_IS_FILTERED: 'CHANGE_IS_FILTERED',
};
