import { OPERATIONS } from "./operations.ts";

export const OPERATIONS_WITHOUT_SESSION = [
	OPERATIONS.AUTHORIZE,
	OPERATIONS.REGISTER,
	OPERATIONS.FETCH_CATEGORIES,
	OPERATIONS.FETCH_PRODUCTS,
	OPERATIONS.FETCH_PRODUCT,
] as const;
